### PR TITLE
Symfony 4.0 support

### PR DESCRIPTION
**Pull request by umpirsky**
@ShonM Please review when you get chance. Thanks.

### CODE REVIEW

**Comment by ShonM** [comment]
I don't need to review this. There's a very strict, factual pass condition: It works. Show evidence of that and merge away.

**Comment by umpirsky** [comment]
OK, will test and merge afterwards, thanks.

**Comment by umpirsky** [comment]
@ShonM [CV-60699](https://chesscom.atlassian.net/browse/CV-60699) passed QA. Can you please merge this so we can proceed with the upgrade?

**Comment by umpirsky** [comment]
@ShonM Packagist is still not updated? https://packagist.org/packages/shonm/php-resque-pool#dev-distribute

Is there a hook missing?

**Comment by ShonM** [comment]
Specify the exact commit hash.

**Comment by umpirsky** [comment]
I did:

```
php composer.phar update shonm/php-resque-pool
    1/2:	http://packagist.org/p/provider-latest$dadb8ad25dc755db16798cf52250515306ed47d43e6acb13c042e292708dacac.json
    2/2:	http://packagist.org/p/provider-2018-04$0df407b8d5c150d53222d37518afa454542c8a666c8b61381c62e32227ec3635.json
    Finished: success: 2, skipped: 0, failure: 0, total: 2
Loading composer repositories with package information
Updating dependencies (including require-dev)                                               
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for shonm/php-resque-pool dev-distribute#2e9a0856acf2d6c85d315e17024a65f1ec547dca -> satisfiable by shonm/php-resque-pool[dev-distribute].
    - Conclusion: remove symfony/symfony v4.0.10
    - Conclusion: don't install symfony/symfony v4.0.10
    - shonm/php-resque-pool dev-distribute requires symfony/yaml ~2.8|~3.0 -> satisfiable by symfony/yaml[v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.32, v2.8.33, v2.8.34, v2.8.35, v2.8.36, v2.8.37, v2.8.38, v2.8.39, v2.8.4, v2.8.40, v2.8.41, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - Installation request for symfony/symfony (locked at v4.0.10, required as 4.0.*) -> satisfiable by symfony/symfony[v4.0.10].

```

**Comment by ShonM** [comment]
And that says the issue is not that Packagist is not up to date, it says `shonm/php-resque-pool dev-distribute requires symfony/yaml ~2.8|~3.0`

**Comment by umpirsky** [comment]
But it does not https://github.com/ShonM/php-resque-pool/blob/distribute/composer.json#L20

**Comment by umpirsky** [comment]
I think composer reads data from packagist, and data is not updated there. While I used [dev-SS/symfony-4.0](https://github.com/ChessCom/chess/pull/25194/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R113) it worked without issues.

**Comment by ShonM** [comment]
Signed into Packagist, forced update, it said license was not valid and the package would not be updated until it was fixed, fixed it, updated, done.

**Comment by umpirsky** [comment]
Worked now, thanks!

**Pull request merged**
